name: matrix
on: push

jobs:
  get-matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        version: [12,14]
    runs-on: ${{metrix.os}}
    steps:
    - name: check metrix
      run: |
        echo ${{ matrix.os }}
        echo ${{ matrix.version }}
