name: tag-filter
on:
  push:
    tags:
      - 'v[0.9]+.[0.9]+.[0.9]+' # v1.0.0 or v2.2.2 (O) / v1.1 or 1.0.0 (X)

jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello